version: '3.1'

volumes:
  postgres_volume:

services:
  pg-local:
    image: postgres
    env_file:
      - .env
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql